# Generated by Django 5.0.6 on 2024-07-11 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Silla',
            fields=[
                ('id_Sillas', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('precio', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('imagen', models.CharField(max_length=100)),
            ],
        ),
    ]
